# Generated by Django 3.2.12 on 2022-12-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('seats_left', models.IntegerField()),
                ('allow_pets', models.BooleanField()),
                ('leave_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('begin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begin_city', to='ideas.city')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ideas.user')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city', to='ideas.city')),
                ('passengers', models.ManyToManyField(to='ideas.User')),
            ],
        ),
    ]
