# Generated by Django 4.1.4 on 2022-12-14 19:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_city_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
